### PR TITLE
Smoothed map for region of the sky

### PR DESCRIPTION
**Pull request by bwvdnbro**
My master's student wants to investigate the impact of map resolution on the statistics of the dispersion measure in the lightcone maps. For this, he needs to be able to generate HEALpix maps at even higher resolution that the `nside=16384` that we use. This is not practical for a full sky map.

I have attempted to change the `make_full_sky_map` function a bit so that it can also generate the map for a smaller region on the sky. While that seems to work, I imagine there are still some issues:
 - I'm not sure the smoothing is done correctly at the boundary of the region
 - the function still generates a full sky map, but only fills the pixels for the selected region. While the file size will probably be fine if you use compression, I'm not sure the full sky map would fit in memory.
 - the parallelisation does not work properly, since that uses full map chunks, and not region chunks.

I have also included some bug fixes that were required to make things work.

@jchelly any thoughts on this? I'm happy to spend some more time on addressing these issues, but maybe you have other ideas or suggestions, or see other potential issues?

### CODE REVIEW

**Comment by jchelly** [comment]
I think the problem at the edges of the map will be that there will be particles with centres outside the region which should be contributing to the map because of their smoothing lengths but they don't get read in. The simple fix would be to read a larger patch of sky than the part we want to map, but then we need an upper limit on the smoothing length and it might be a large at low redshift. If it needs to work at low redshift maybe we could extract the large smoothing length particles and always check if they contribute regardless of position on the sky.

The other problem is that we will need to store a partial map somehow. One option (off the top of my head, and not thought through properly!) would be to use the nested pixel scheme and use a low resolution healpix map to define the area to map and to split the map between MPI ranks. We could then have an array for each low resolution pixel we're interested in that contains the high resolution pixel data.

**Comment by jchelly** [comment]
The MPI communication would need to be rethought then though, because it's based on each rank having a slice in latitude at the moment.

**Comment by jchelly** [comment]
I suppose an easier but less efficient solution would be to keep using the ring pixel scheme and store the map for a limited range in lattude which covers the target area. Then we could continue to store different latitude ranges on different MPI ranks.

**Comment by bwvdnbro** [comment]
Using nested order sounds like a good idea, but I imagine that this will require some rewriting? For this particular application, nested ordering is actually better suited anyway, since that makes it easier to do a pixel-by-pixel comparison between different pixel resolutions.

At low redshift the dispersion measure looks converged enough for our fiducial resolution, so my student is mostly interested in looking at a somewhat higher redshift. There we can probably get away with a buffer region to get rid of edge effects.

**Comment by jchelly** [comment]
Another way to do a partial map would be to rotate the map so that the line of sight is the north pole. Then an angular radius around the line of sight using ring indexing is just the first N pixels of the map, where N increases with the radius.

**Pull request merged**
